name: 💡 Suggest a new feature
description: >
  Have an idea for a new feature or enhancement? Share it with us! [Suggest a new feature](: https://github.com/nsidc/earthaccess/discussions/new?category=ideas)
